### ISSUE TITLE
license

### ISSUE THREAD

**Issue by misterhat** [GeneralUnRest/json2#1]
???

**Comment by ghost** [comment]
the individual files have the appropriate licenses attached to the top of them.

**Comment by misterhat** [comment]
[That doesn't jive with the license you have listed in your package.json](https://github.com/GeneralUnRest/json2/blob/master/package.json#L23). Please re-open!

**Comment by ghost** [comment]
https://github.com/GeneralUnRest/json2/blob/master/LICENSE

**Comment by misterhat** [comment]
bad license

**Comment by ghost** [comment]
lmao. what should I use instead? Lesser GLPv2.1?

how is that going to be enforceable for a program that is, collectively, only like a hundred lines?

ISC is fine and is GPL compatible.

**Comment by misterhat** [comment]
Lesser GPLv*3+*.

**Comment by ghost** [comment]
LGPLv3+ isn't compatible with GPLv2 unless it has "or later version" clause. It's not practical.

**Comment by misterhat** [comment]
GPLv2 is regressive. GPLv3 is the future,
